#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Scoreboard.Droid.Resource", IsApplication=true)]

namespace Scoreboard.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int green = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int text_color = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int wl_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int wl_gray = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001c
			public const int button1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int button2 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int button3 = 2131099678;
			
			// aapt resource value: 0x7f060029
			public const int createGameBtn = 2131099689;
			
			// aapt resource value: 0x7f060001
			public const int dialogText = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int editGameBtn = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int gameImageView1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int gameImageView2 = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int gameImageView3 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int gameImageView4 = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int gameTextView = 2131099657;
			
			// aapt resource value: 0x7f06001f
			public const int games = 2131099679;
			
			// aapt resource value: 0x7f060002
			public const int imageBtn = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int imageView = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int liveStreamImg = 2131099668;
			
			// aapt resource value: 0x7f060020
			public const int newGameBtn = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int newTeam1Player1Image = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int newTeam1Player1Text = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int newTeam1Player2Image = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int newTeam1Player2Text = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int newTeam2Player1Image = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int newTeam2Player1Text = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int newTeam2Player2Image = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int newTeam2Player2Text = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int relativeLayout1 = 2131099675;
			
			// aapt resource value: 0x7f060016
			public const int rowImageView1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int rowImageView2 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int rowImageView3 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int rowImageView4 = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int rowTextView = 2131099672;
			
			// aapt resource value: 0x7f060006
			public const int saveScoreBtn = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int scoreTeam1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int scoreTeam2 = 2131099653;
			
			// aapt resource value: 0x7f06000c
			public const int team1Player1Image = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int team1Player1Text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int team1Player2Image = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int team1Player2Text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int team2Player1Image = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int team2Player1Text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int team2Player2Image = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int team2Player2Text = 2131099667;
			
			// aapt resource value: 0x7f06002a
			public const int userRow = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int users = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditGame = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Game = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listAdapter = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NewGame = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UserAdapter = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int users = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int noImage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Play = 2130837506;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
